DROP DATABASE IF EXISTS ms_products;
CREATE DATABASE ms_products;

GRANT ALL PRIVILEGES ON DATABASE "ms_products" to root;

\c ms_products;

CREATE TABLE IF NOT EXISTS product (
   id int8 generated by default as identity,
   name varchar(255),
   primary key (id)
);
