DROP DATABASE IF EXISTS ms_products;
CREATE DATABASE ms_products;

GRANT ALL PRIVILEGES ON DATABASE "ms_products" to postgres;

\c ms_products;

create table if not exists product (
   id int8 generated by default as identity,
   name varchar(32) not null,
   code varchar(32) not null,
   model varchar(32) not null,
   price float8,
   primary key (id)
);

alter table if exists product
    add constraint UKh3w5r1mx6d0e5c6um32dgyjej unique (code)

