version: '3.7'
services:
  database:
    container_name: database
    image: postgres:12-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./scripts/postgres/01-schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./scripts/postgres/02-data.sql:/docker-entrypoint-initdb.d/02-data.sql

  localstack:
    container_name: localstack
    image: localstack/localstack:latest
    environment:
      - DEFAULT_REGION=us-east-1
      - SERVICES=sns
    ports:
      - "4566:4566"
      - "4571:4571"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    volumes:
      - ./src/main/resources/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
