version: '3.7'
services:
  database:
    image: postgres:12-alpine
    container_name: ms-products-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./scripts/postgres/01-schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./scripts/postgres/02-data.sql:/docker-entrypoint-initdb.d/02-data.sql

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./src/main/resources/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
